# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modelYolov8.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11modelYolov8.proto\")\n\x0cImageRequest\x12\x19\n\x11input_image_paths\x18\x01 \x03(\t\"M\n\x0f\x44ictionaryEntry\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12\x11\n\tprocessed\x18\x02 \x01(\x08\x12\x13\n\x0bresult_path\x18\x03 \x01(\t\"2\n\rImageResponse\x12!\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x10.DictionaryEntry2?\n\x0eImageProcessor\x12-\n\x0cProcessImage\x12\r.ImageRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modelYolov8_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=21
  _globals['_IMAGEREQUEST']._serialized_end=62
  _globals['_DICTIONARYENTRY']._serialized_start=64
  _globals['_DICTIONARYENTRY']._serialized_end=141
  _globals['_IMAGERESPONSE']._serialized_start=143
  _globals['_IMAGERESPONSE']._serialized_end=193
  _globals['_IMAGEPROCESSOR']._serialized_start=195
  _globals['_IMAGEPROCESSOR']._serialized_end=258
# @@protoc_insertion_point(module_scope)
